public with sharing class WorkProposalUtil {
/*	
    public static Set<Id> processedOptys = new Set<Id>();
    
    public static void createProject(Map<Id, Id> optyProposalMap, Map<Id, String> projectTypeMap){
       
        Map<Id, Id> modifiedOptyMap = new Map<Id, Id>();
        
        for(Id optyId : optyProposalMap.KeySet()){
        	
            if(!processedOptys.contains(optyId)){
                modifiedOptyMap.put(optyId, optyProposalMap.get(optyId));
            }
        }
        
        if(!modifiedOptyMap.isEmpty()){
        	
            processedOptys.addall(modifiedOptyMap.keySet());
            WorkflowManagement wfManagementObj = new WorkflowManagement();
            wfManagementObj.createProject(modifiedOptyMap, projectTypeMap);
        }
    }
    
*/    
}